### PR TITLE
Adding documentation for software

### PR DESCRIPTION
**Pull request by vsoch**
This is a work in progress to add pages to the base site to install software, so far I've done:

 - how to install your own software (a derivation of farmshare) but spruced up a bit!

image

 - added a page for rclone, a more general derivation of the Sherlock addition (still not reviewed).
 - added the page (start) for SLURM, and a subpage for sbatch examples. We will likely also want examples with job arrays and general slurm commands for job submission.
 - getting started (transfer files)
 - added start of tutorials grouping

I've also updated the template with master (a few bug fixes since last working on it) and added the html2md.py script since it's helpful to convert rendered mediawiki pages to markdown.

### CODE REVIEW

**Comment by romxero** [comment]
Thank you for linking the carpentry stuff. You were correct in your assessment. We don't want to copy material. It was unbeknownst to me that it was copied.

**Comment by vsoch** [comment]
I'm worried that some of the other pages from the wiki are from tutorials too (e.g. the transfer files one, and accessing software). @mpiercy could you take a look and let me know which ones were from carpentry? I'll remove asap!

**Comment by romxero** [comment]
Mark at the moment is on vacation, He'll be back next week =/.

**Comment by vsoch** [comment]
ah thanks for letting me know! I actually think I know the answer - the pages that are from tutorials (I think) are:

 -  transfer-files.md
 - accessing-software.md
 - the best practices page

The installing-software.md page I did a lot of editing to, so I think it's okay to keep. For the others, I'll remove these from the PR so you can still review.

**Comment by romxero** [comment]
Thanks V!

**Comment by vsoch** [comment]
okay - so this commit https://github.com/stanford-rc/stanford-rc.github.io/pull/3/commits/486b0ac1a943b5f44cfbfdc8cf022cf785dbb223 should remove the software carpentry pages, keeping the "how-to-install" because that's been customized quite a bit (nyancat!)

This commit https://github.com/stanford-rc/stanford-rc.github.io/pull/3/commits/261252922168a3756e3ef1c90ae567af61b0023e is rebasing with mkdocs-jekyll, specifically adding support for quizzes!  https://vsoch.github.io/mkdocs-jekyll/docs/extras/example-quiz#example-quiz

Do you want to add quizzes? We should add quizzes (but different PR of course!)

After these changes, it should be ready for review. This should check off a few items from the list on slack (for batch job examples and software install) and we can then discuss what to do next.

**Comment by romxero** [comment]
Lets add quizes in another PR. It reminds me of a project I was trying to get funding for. An intelligent textbook with AI directed quizes. Thats overkill but I think it will be a good thing to add.

**Comment by vsoch** [comment]
Would you like me to remove the dummy quiz file before you can review? It isn't rendered anywhere so it should be okay to leave, and make it easier when we decide to add quizzes in another PR. The include templates are good to stay - they came from the rebase.

**Comment by romxero** [comment]
Sure!

**Comment by vsoch** [comment]
Removed.

**Comment by romxero** [comment]
lol sorry I meant sure you can leave it in.

**Comment by vsoch** [comment]
Oh, sorry, I thought you were answering the question! It's actually ok either way :) Please review at your leisure! And assign me to anything else that can be done.

**Pull request merged**
